### PR TITLE
Laravel 8 Compatibility

### PR DESCRIPTION
**Pull request by pkracer**
This PR updates the `laravel/framework` dependency to work with either Laravel 7 or 8. 

The default route namespace has been removed from the `WinkServiceProvider`. All controller declarations have been updated to use the standard PHP callable syntax.

### CODE REVIEW

**Comment by topclaudy** [comment]
Please merge this.

**Comment by vinzce** [comment]
I need this

**Comment by relaypilot** [comment]
Can I edit my vendor files directly to force those changes (while waiting for an official update)? 
Or is there a cleaner way to do it?

**Comment by pkracer** [comment]
While waiting for this to be merged, you can fork this repository, update your fork with the changes from this PR, and use it in your project instead. 

For example, I forked this repository, cloned my fork down to a directory named `wink-fork`, updated my fork with the changes from this PR, and then updated my project's `composer.json` to use my fork instead.

composer.json
```
    "repositories": [
        {
            "type": "path",
            "url": "../wink-fork",
            "options": {
                "symlink": false
            }
        }
    ]
```

**Comment by topclaudy** [comment]
@pkracer If you don't want to fork, use https://github.com/cweagans/composer-patches

**Comment by relaypilot** [comment]
@pkracer Thank you for the tip! It works perfectly on local.

However when I deploy on my prod server, the composer install command fails:
When deploying, the following command is ran by my server:

    git pull origin master`
    composer install --no-interaction --prefer-dist --optimize-autoloader

And the error output:

    Source path "../wink-fork" is not found for package themsaid/wink

**Comment by pkracer** [comment]
I'm guessing that it's looking for a directory (wink-fork) that doesn't exist. You just need to clone the fork down on your prod server as well, the same as you did for local. Make sure you commit those PR changes to your fork first!

**Pull request merged**
